isEnabled: true
image:
  imageFrom: europe-west3-docker.pkg.dev/brdata-dev/cloud-deploy-images/wtwm-application-base-image
run:
  command: /opt/venv/bin/python3.9 -m uvicorn api:APP --host 0.0.0.0 --port 3000
  envs:
    - name: LC_ALL
      value: "de_DE.UTF-8"
    - name: LANG
      value: "de_DE.UTF-8"
    - name: LANGUAGE
      value: "de_DE.UTF-8"
    - name: TZ
      value: "CET"
    - name: FORWARDED_ALLOW_IPS
      value: '*'
    - name: GPT2_MODEL_PATH
      value: "/data/storage/gpt2/"
    - name: BUGG_MODEL_V1_PATH
      value: "/data/storage/bugg_model_v1/"
    - name: BACKUP_PATH
      value: "/data/storage/backup/"
    - name: BASELINE_SOURCE_FILE
      value: "/data/storage/baseline_regex_collection.txt"
    - name: MDR_COMMENT_ENDPOINT_TOKEN
      value: sm://{{.projectId}}/mdr-comment-endpoint-bearer
    - name: MDR_COMMENT_ENDPOINT
      value: sm://{{.projectId}}/mdr-comment-endpoint
    - name: BR_COMMENT_ENDPOINT_TOKEN
      value: sm://{{.projectId}}/br-comment-endpoint-bearer
    - name: BR_COMMENT_ENDPOINT
      value: sm://{{.projectId}}/br-comment-endpoint
    - name: TABLE_ID
      value: "test_table"
    - name: IDA_BIGQUERY_CREDENTIAL_PATH
      value: sm://{{.projectId}}/wtwm-db-credential-path
    - name: MDR_TARGET
      value: sm://{{.projectId}}/wtwm-mdr-target
    - name: BR_TARGET
      value: sm://{{.projectId}}/wtwm-br-target
settings:
  type: service
  persistentBucket: wtwm-data-bucket
  database:
    type: postgresql
    size: 15
    frontend: true