isEnabled: true
image:
  imageFrom: ubuntu:20.04
build:
  command: "TZ=Europe/Berlin \
            && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
            && echo $TZ > /etc/timezone \
            && apt-get -y update \
            && apt-get -y install locales \
            && sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen \
            && locale-gen \
            && apt-get -y install python3.9 python3.9-venv \
            && mkdir /opt/venv
            && python3.9 -m venv /opt/venv
            && /opt/venv/bin/python3.9 -m pip install --upgrade pip \
            && /opt/venv/bin/python3.9 -m pip install -r requirements.txt"
run:
  command: /opt/venv/bin/python3.9 -m uvicorn api:APP --host 0.0.0.0 --port 3000
  envs:
    - name: LC_ALL
      value: "de_DE.UTF-8"
    - name: LANG
      value: "de_DE.UTF-8"
    - name: LANGUAGE
      value: "de_DE.UTF-8"
    - name: TZ
      value: "CET"
    - name: MODEL_PATH
      value: "/data/storage/detect_mentions/"
    - name: BACKUP_PATH
      value: "/data/storage/backup/"
    - name: BASELINE_SOURCE_FILE
      value: "/data/storage/baseline_regex_collection.txt"
    - name: MDR_COMMENT_ENDPOINT_TOKEN
      value: sm://{{.projectId}}/mdr-comment-endpoint-bearer
    - name: MDR_COMMENT_ENDPOINT
      value: sm://{{.projectId}}/mdr-comment-endpoint
    - name: BR_COMMENT_ENDPOINT_TOKEN
      value: sm://{{.projectId}}/br-comment-endpoint-bearer
    - name: BR_COMMENT_ENDPOINT
      value: sm://{{.projectId}}/br-comment-endpoint
    - name: TABLE_ID
      value: "test_table"
    - name: IDA_BIGQUERY_CREDENTIAL_PATH
      value: sm://{{.projectId}}/wtwm-db-credential-path
    - name: MDR_TARGET
      value: sm://{{.projectId}}/wtwm-mdr-target
    - name: BR_TARGET
      value: sm://{{.projectId}}/wtwm-br-target
settings:
  type: service
  persistentBucket: wtwm-data-bucket
  database:
    type: postgresql
    size: 15
    frontend: true