isEnabled: false
image:
  preset: python
build:
  command: yarn
run:
  command: python run_example.py
  envs:
    - name: STAGE
      value: develop
    - name: HOST
      value: 0.0.0.0
    - name: NAME
      value: wtwm-topic-modelling
    - name: PORT
      value: '3000'
    - name: URL
      value: https://www.wtwm-topic-modelling.interaktiv.br.de/
settings:
  type: service
  persistentVolume:
    mountPath: /data/test
    size: 1
